version: '3.8'
 
services:
  postgres_db:
    container_name: postgres_db
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - users
    
  users_backend:
    container_name: users_backend
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    networks:
      - users

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - users
    restart: unless-stopped
  
volumes:
  dbdata:

networks:
  users:
    driver: users